name: 'Clojure Env'
description: 'Setup a clojure environment'
runs:
  using: "composite"
  steps:
    - name: Restore maven
      uses: actions/cache@v2
      id: restore-maven
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Restore gitlibs
      uses: actions/cache@v2
      id: restore-gitlibs
      with:
        path: ~/.gitlibs
        key: ${{ runner.os }}-gitlibs-${{ hashFiles('deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-gitlibs-

    - name: Prepare java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - uses: DeLaGuardo/setup-clojure@3.5
      with:
        cli: 1.10.3.986

    - name: Fetch dependencies
      # Clojure on windows needs to be run on powershell.
      # Powershell is also present on other platforms so we can use it for all.
      shell: pwsh
      if: steps.restore-maven.outputs.cache-hit != 'true'
      run: clojure -P
