name: 'Node Env'
description: 'Setup a node environment'
runs:
  using: "composite"
  steps:
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
      shell: bash

    - name: Restore yarn cache
      uses: actions/cache@v2
      id: restore-yarn
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-v1-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-v1-yarn-

    - name: Fetch yarn dependencies
      run: yarn install --frozen-lockfile --network-timeout 10000000
      shell: bash
